// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'batch-complete'
  | 'batch-progress'
  | 'batch-skipped'
  | 'conversion-failed'
  | 'conversion-started'
  | 'conversion-success'
  | 'engine-not-found'
  | 'menu-convert-all'
  | 'menu-convert-selected'
  | 'pref-attach-result'
  | 'pref-auto-convert'
  | 'pref-converter-engine'
  | 'pref-engine-docling'
  | 'pref-engine-pymupdf4llm'
  | 'pref-help'
  | 'pref-output-directory'
  | 'pref-output-directory-desc'
  | 'pref-python-path'
  | 'pref-python-path-desc'
  | 'pref-title'
  | 'prefs-title'
  | 'python-not-found'
  | 'startup-begin'
  | 'startup-finish'
  | 'zoteromd-name';
