// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "autoConvert": boolean;
      "converterEngine": string;
      "pythonPath": string;
      "outputDirectory": string;
      "attachResult": boolean;
    };
  }
}
